/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ProprietariosRouteImport } from './routes/proprietarios'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CasasRouteImport } from './routes/casas'
import { Route as CandidaturaRouteImport } from './routes/candidatura'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as OwnerIndexRouteImport } from './routes/owner.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PortalRenovacaoRouteImport } from './routes/portal.renovacao'
import { Route as PortalPerfilRouteImport } from './routes/portal.perfil'
import { Route as PortalPagamentosRouteImport } from './routes/portal.pagamentos'
import { Route as PortalManualRouteImport } from './routes/portal.manual'
import { Route as PortalEstadiaRouteImport } from './routes/portal.estadia'
import { Route as PortalContratosRouteImport } from './routes/portal.contratos'
import { Route as PortalComunidadeRouteImport } from './routes/portal.comunidade'
import { Route as PortalComunicadosRouteImport } from './routes/portal.comunicados'
import { Route as PortalChamadosRouteImport } from './routes/portal.chamados'
import { Route as OwnerVistoriasRouteImport } from './routes/owner.vistorias'
import { Route as OwnerMensagensRouteImport } from './routes/owner.mensagens'
import { Route as OwnerManutencaoRouteImport } from './routes/owner.manutencao'
import { Route as OwnerFinanceiroRouteImport } from './routes/owner.financeiro'
import { Route as OwnerDocumentosRouteImport } from './routes/owner.documentos'
import { Route as ImprimirContratoIdRouteImport } from './routes/imprimir-contrato.$id'
import { Route as CasasIdRouteImport } from './routes/casas.$id'
import { Route as AssinarDocumentIdRouteImport } from './routes/assinar.$documentId'
import { Route as AdminVistoriasRouteImport } from './routes/admin.vistorias'
import { Route as AdminQuartosRouteImport } from './routes/admin.quartos'
import { Route as AdminProprietariosRouteImport } from './routes/admin.proprietarios'
import { Route as AdminMoradorasRouteImport } from './routes/admin.moradoras'
import { Route as AdminModelosContratoRouteImport } from './routes/admin.modelos-contrato'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminFornecedoresRouteImport } from './routes/admin.fornecedores'
import { Route as AdminFinanceiroRouteImport } from './routes/admin.financeiro'
import { Route as AdminContratosRouteImport } from './routes/admin.contratos'
import { Route as AdminComunicadosRouteImport } from './routes/admin.comunicados'
import { Route as AdminChamadosRouteImport } from './routes/admin.chamados'
import { Route as AdminCasasRouteImport } from './routes/admin.casas'
import { Route as AdminCandidaturasRouteImport } from './routes/admin.candidaturas'
import { Route as AdminAcessosRouteImport } from './routes/admin.acessos'
import { Route as AdminContratosIdRouteImport } from './routes/admin.contratos.$id'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ProprietariosRoute = ProprietariosRouteImport.update({
  id: '/proprietarios',
  path: '/proprietarios',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CasasRoute = CasasRouteImport.update({
  id: '/casas',
  path: '/casas',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidaturaRoute = CandidaturaRouteImport.update({
  id: '/candidatura',
  path: '/candidatura',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PortalRenovacaoRoute = PortalRenovacaoRouteImport.update({
  id: '/renovacao',
  path: '/renovacao',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPerfilRoute = PortalPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPagamentosRoute = PortalPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => PortalRoute,
} as any)
const PortalManualRoute = PortalManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => PortalRoute,
} as any)
const PortalEstadiaRoute = PortalEstadiaRouteImport.update({
  id: '/estadia',
  path: '/estadia',
  getParentRoute: () => PortalRoute,
} as any)
const PortalContratosRoute = PortalContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => PortalRoute,
} as any)
const PortalComunidadeRoute = PortalComunidadeRouteImport.update({
  id: '/comunidade',
  path: '/comunidade',
  getParentRoute: () => PortalRoute,
} as any)
const PortalComunicadosRoute = PortalComunicadosRouteImport.update({
  id: '/comunicados',
  path: '/comunicados',
  getParentRoute: () => PortalRoute,
} as any)
const PortalChamadosRoute = PortalChamadosRouteImport.update({
  id: '/chamados',
  path: '/chamados',
  getParentRoute: () => PortalRoute,
} as any)
const OwnerVistoriasRoute = OwnerVistoriasRouteImport.update({
  id: '/vistorias',
  path: '/vistorias',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerMensagensRoute = OwnerMensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerManutencaoRoute = OwnerManutencaoRouteImport.update({
  id: '/manutencao',
  path: '/manutencao',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerFinanceiroRoute = OwnerFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerDocumentosRoute = OwnerDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => OwnerRoute,
} as any)
const ImprimirContratoIdRoute = ImprimirContratoIdRouteImport.update({
  id: '/imprimir-contrato/$id',
  path: '/imprimir-contrato/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CasasIdRoute = CasasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CasasRoute,
} as any)
const AssinarDocumentIdRoute = AssinarDocumentIdRouteImport.update({
  id: '/assinar/$documentId',
  path: '/assinar/$documentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVistoriasRoute = AdminVistoriasRouteImport.update({
  id: '/vistorias',
  path: '/vistorias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuartosRoute = AdminQuartosRouteImport.update({
  id: '/quartos',
  path: '/quartos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProprietariosRoute = AdminProprietariosRouteImport.update({
  id: '/proprietarios',
  path: '/proprietarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMoradorasRoute = AdminMoradorasRouteImport.update({
  id: '/moradoras',
  path: '/moradoras',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModelosContratoRoute = AdminModelosContratoRouteImport.update({
  id: '/modelos-contrato',
  path: '/modelos-contrato',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFornecedoresRoute = AdminFornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContratosRoute = AdminContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComunicadosRoute = AdminComunicadosRouteImport.update({
  id: '/comunicados',
  path: '/comunicados',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChamadosRoute = AdminChamadosRouteImport.update({
  id: '/chamados',
  path: '/chamados',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCasasRoute = AdminCasasRouteImport.update({
  id: '/casas',
  path: '/casas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCandidaturasRoute = AdminCandidaturasRouteImport.update({
  id: '/candidaturas',
  path: '/candidaturas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAcessosRoute = AdminAcessosRouteImport.update({
  id: '/acessos',
  path: '/acessos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContratosIdRoute = AdminContratosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminContratosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/candidatura': typeof CandidaturaRoute
  '/casas': typeof CasasRouteWithChildren
  '/contato': typeof ContatoRoute
  '/owner': typeof OwnerRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/proprietarios': typeof ProprietariosRoute
  '/sobre': typeof SobreRoute
  '/admin/acessos': typeof AdminAcessosRoute
  '/admin/candidaturas': typeof AdminCandidaturasRoute
  '/admin/casas': typeof AdminCasasRoute
  '/admin/chamados': typeof AdminChamadosRoute
  '/admin/comunicados': typeof AdminComunicadosRoute
  '/admin/contratos': typeof AdminContratosRouteWithChildren
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/fornecedores': typeof AdminFornecedoresRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/modelos-contrato': typeof AdminModelosContratoRoute
  '/admin/moradoras': typeof AdminMoradorasRoute
  '/admin/proprietarios': typeof AdminProprietariosRoute
  '/admin/quartos': typeof AdminQuartosRoute
  '/admin/vistorias': typeof AdminVistoriasRoute
  '/assinar/$documentId': typeof AssinarDocumentIdRoute
  '/casas/$id': typeof CasasIdRoute
  '/imprimir-contrato/$id': typeof ImprimirContratoIdRoute
  '/owner/documentos': typeof OwnerDocumentosRoute
  '/owner/financeiro': typeof OwnerFinanceiroRoute
  '/owner/manutencao': typeof OwnerManutencaoRoute
  '/owner/mensagens': typeof OwnerMensagensRoute
  '/owner/vistorias': typeof OwnerVistoriasRoute
  '/portal/chamados': typeof PortalChamadosRoute
  '/portal/comunicados': typeof PortalComunicadosRoute
  '/portal/comunidade': typeof PortalComunidadeRoute
  '/portal/contratos': typeof PortalContratosRoute
  '/portal/estadia': typeof PortalEstadiaRoute
  '/portal/manual': typeof PortalManualRoute
  '/portal/pagamentos': typeof PortalPagamentosRoute
  '/portal/perfil': typeof PortalPerfilRoute
  '/portal/renovacao': typeof PortalRenovacaoRoute
  '/admin/': typeof AdminIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/admin/contratos/$id': typeof AdminContratosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/candidatura': typeof CandidaturaRoute
  '/casas': typeof CasasRouteWithChildren
  '/contato': typeof ContatoRoute
  '/proprietarios': typeof ProprietariosRoute
  '/sobre': typeof SobreRoute
  '/admin/acessos': typeof AdminAcessosRoute
  '/admin/candidaturas': typeof AdminCandidaturasRoute
  '/admin/casas': typeof AdminCasasRoute
  '/admin/chamados': typeof AdminChamadosRoute
  '/admin/comunicados': typeof AdminComunicadosRoute
  '/admin/contratos': typeof AdminContratosRouteWithChildren
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/fornecedores': typeof AdminFornecedoresRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/modelos-contrato': typeof AdminModelosContratoRoute
  '/admin/moradoras': typeof AdminMoradorasRoute
  '/admin/proprietarios': typeof AdminProprietariosRoute
  '/admin/quartos': typeof AdminQuartosRoute
  '/admin/vistorias': typeof AdminVistoriasRoute
  '/assinar/$documentId': typeof AssinarDocumentIdRoute
  '/casas/$id': typeof CasasIdRoute
  '/imprimir-contrato/$id': typeof ImprimirContratoIdRoute
  '/owner/documentos': typeof OwnerDocumentosRoute
  '/owner/financeiro': typeof OwnerFinanceiroRoute
  '/owner/manutencao': typeof OwnerManutencaoRoute
  '/owner/mensagens': typeof OwnerMensagensRoute
  '/owner/vistorias': typeof OwnerVistoriasRoute
  '/portal/chamados': typeof PortalChamadosRoute
  '/portal/comunicados': typeof PortalComunicadosRoute
  '/portal/comunidade': typeof PortalComunidadeRoute
  '/portal/contratos': typeof PortalContratosRoute
  '/portal/estadia': typeof PortalEstadiaRoute
  '/portal/manual': typeof PortalManualRoute
  '/portal/pagamentos': typeof PortalPagamentosRoute
  '/portal/perfil': typeof PortalPerfilRoute
  '/portal/renovacao': typeof PortalRenovacaoRoute
  '/admin': typeof AdminIndexRoute
  '/owner': typeof OwnerIndexRoute
  '/portal': typeof PortalIndexRoute
  '/admin/contratos/$id': typeof AdminContratosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/candidatura': typeof CandidaturaRoute
  '/casas': typeof CasasRouteWithChildren
  '/contato': typeof ContatoRoute
  '/owner': typeof OwnerRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/proprietarios': typeof ProprietariosRoute
  '/sobre': typeof SobreRoute
  '/admin/acessos': typeof AdminAcessosRoute
  '/admin/candidaturas': typeof AdminCandidaturasRoute
  '/admin/casas': typeof AdminCasasRoute
  '/admin/chamados': typeof AdminChamadosRoute
  '/admin/comunicados': typeof AdminComunicadosRoute
  '/admin/contratos': typeof AdminContratosRouteWithChildren
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/fornecedores': typeof AdminFornecedoresRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/modelos-contrato': typeof AdminModelosContratoRoute
  '/admin/moradoras': typeof AdminMoradorasRoute
  '/admin/proprietarios': typeof AdminProprietariosRoute
  '/admin/quartos': typeof AdminQuartosRoute
  '/admin/vistorias': typeof AdminVistoriasRoute
  '/assinar/$documentId': typeof AssinarDocumentIdRoute
  '/casas/$id': typeof CasasIdRoute
  '/imprimir-contrato/$id': typeof ImprimirContratoIdRoute
  '/owner/documentos': typeof OwnerDocumentosRoute
  '/owner/financeiro': typeof OwnerFinanceiroRoute
  '/owner/manutencao': typeof OwnerManutencaoRoute
  '/owner/mensagens': typeof OwnerMensagensRoute
  '/owner/vistorias': typeof OwnerVistoriasRoute
  '/portal/chamados': typeof PortalChamadosRoute
  '/portal/comunicados': typeof PortalComunicadosRoute
  '/portal/comunidade': typeof PortalComunidadeRoute
  '/portal/contratos': typeof PortalContratosRoute
  '/portal/estadia': typeof PortalEstadiaRoute
  '/portal/manual': typeof PortalManualRoute
  '/portal/pagamentos': typeof PortalPagamentosRoute
  '/portal/perfil': typeof PortalPerfilRoute
  '/portal/renovacao': typeof PortalRenovacaoRoute
  '/admin/': typeof AdminIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/admin/contratos/$id': typeof AdminContratosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/candidatura'
    | '/casas'
    | '/contato'
    | '/owner'
    | '/portal'
    | '/proprietarios'
    | '/sobre'
    | '/admin/acessos'
    | '/admin/candidaturas'
    | '/admin/casas'
    | '/admin/chamados'
    | '/admin/comunicados'
    | '/admin/contratos'
    | '/admin/financeiro'
    | '/admin/fornecedores'
    | '/admin/leads'
    | '/admin/modelos-contrato'
    | '/admin/moradoras'
    | '/admin/proprietarios'
    | '/admin/quartos'
    | '/admin/vistorias'
    | '/assinar/$documentId'
    | '/casas/$id'
    | '/imprimir-contrato/$id'
    | '/owner/documentos'
    | '/owner/financeiro'
    | '/owner/manutencao'
    | '/owner/mensagens'
    | '/owner/vistorias'
    | '/portal/chamados'
    | '/portal/comunicados'
    | '/portal/comunidade'
    | '/portal/contratos'
    | '/portal/estadia'
    | '/portal/manual'
    | '/portal/pagamentos'
    | '/portal/perfil'
    | '/portal/renovacao'
    | '/admin/'
    | '/owner/'
    | '/portal/'
    | '/admin/contratos/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/candidatura'
    | '/casas'
    | '/contato'
    | '/proprietarios'
    | '/sobre'
    | '/admin/acessos'
    | '/admin/candidaturas'
    | '/admin/casas'
    | '/admin/chamados'
    | '/admin/comunicados'
    | '/admin/contratos'
    | '/admin/financeiro'
    | '/admin/fornecedores'
    | '/admin/leads'
    | '/admin/modelos-contrato'
    | '/admin/moradoras'
    | '/admin/proprietarios'
    | '/admin/quartos'
    | '/admin/vistorias'
    | '/assinar/$documentId'
    | '/casas/$id'
    | '/imprimir-contrato/$id'
    | '/owner/documentos'
    | '/owner/financeiro'
    | '/owner/manutencao'
    | '/owner/mensagens'
    | '/owner/vistorias'
    | '/portal/chamados'
    | '/portal/comunicados'
    | '/portal/comunidade'
    | '/portal/contratos'
    | '/portal/estadia'
    | '/portal/manual'
    | '/portal/pagamentos'
    | '/portal/perfil'
    | '/portal/renovacao'
    | '/admin'
    | '/owner'
    | '/portal'
    | '/admin/contratos/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/candidatura'
    | '/casas'
    | '/contato'
    | '/owner'
    | '/portal'
    | '/proprietarios'
    | '/sobre'
    | '/admin/acessos'
    | '/admin/candidaturas'
    | '/admin/casas'
    | '/admin/chamados'
    | '/admin/comunicados'
    | '/admin/contratos'
    | '/admin/financeiro'
    | '/admin/fornecedores'
    | '/admin/leads'
    | '/admin/modelos-contrato'
    | '/admin/moradoras'
    | '/admin/proprietarios'
    | '/admin/quartos'
    | '/admin/vistorias'
    | '/assinar/$documentId'
    | '/casas/$id'
    | '/imprimir-contrato/$id'
    | '/owner/documentos'
    | '/owner/financeiro'
    | '/owner/manutencao'
    | '/owner/mensagens'
    | '/owner/vistorias'
    | '/portal/chamados'
    | '/portal/comunicados'
    | '/portal/comunidade'
    | '/portal/contratos'
    | '/portal/estadia'
    | '/portal/manual'
    | '/portal/pagamentos'
    | '/portal/perfil'
    | '/portal/renovacao'
    | '/admin/'
    | '/owner/'
    | '/portal/'
    | '/admin/contratos/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CandidaturaRoute: typeof CandidaturaRoute
  CasasRoute: typeof CasasRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  OwnerRoute: typeof OwnerRouteWithChildren
  PortalRoute: typeof PortalRouteWithChildren
  ProprietariosRoute: typeof ProprietariosRoute
  SobreRoute: typeof SobreRoute
  AssinarDocumentIdRoute: typeof AssinarDocumentIdRoute
  ImprimirContratoIdRoute: typeof ImprimirContratoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proprietarios': {
      id: '/proprietarios'
      path: '/proprietarios'
      fullPath: '/proprietarios'
      preLoaderRoute: typeof ProprietariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casas': {
      id: '/casas'
      path: '/casas'
      fullPath: '/casas'
      preLoaderRoute: typeof CasasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidatura': {
      id: '/candidatura'
      path: '/candidatura'
      fullPath: '/candidatura'
      preLoaderRoute: typeof CandidaturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/owner/': {
      id: '/owner/'
      path: '/'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/portal/renovacao': {
      id: '/portal/renovacao'
      path: '/renovacao'
      fullPath: '/portal/renovacao'
      preLoaderRoute: typeof PortalRenovacaoRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/perfil': {
      id: '/portal/perfil'
      path: '/perfil'
      fullPath: '/portal/perfil'
      preLoaderRoute: typeof PortalPerfilRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/pagamentos': {
      id: '/portal/pagamentos'
      path: '/pagamentos'
      fullPath: '/portal/pagamentos'
      preLoaderRoute: typeof PortalPagamentosRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/manual': {
      id: '/portal/manual'
      path: '/manual'
      fullPath: '/portal/manual'
      preLoaderRoute: typeof PortalManualRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/estadia': {
      id: '/portal/estadia'
      path: '/estadia'
      fullPath: '/portal/estadia'
      preLoaderRoute: typeof PortalEstadiaRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/contratos': {
      id: '/portal/contratos'
      path: '/contratos'
      fullPath: '/portal/contratos'
      preLoaderRoute: typeof PortalContratosRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/comunidade': {
      id: '/portal/comunidade'
      path: '/comunidade'
      fullPath: '/portal/comunidade'
      preLoaderRoute: typeof PortalComunidadeRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/comunicados': {
      id: '/portal/comunicados'
      path: '/comunicados'
      fullPath: '/portal/comunicados'
      preLoaderRoute: typeof PortalComunicadosRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/chamados': {
      id: '/portal/chamados'
      path: '/chamados'
      fullPath: '/portal/chamados'
      preLoaderRoute: typeof PortalChamadosRouteImport
      parentRoute: typeof PortalRoute
    }
    '/owner/vistorias': {
      id: '/owner/vistorias'
      path: '/vistorias'
      fullPath: '/owner/vistorias'
      preLoaderRoute: typeof OwnerVistoriasRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/mensagens': {
      id: '/owner/mensagens'
      path: '/mensagens'
      fullPath: '/owner/mensagens'
      preLoaderRoute: typeof OwnerMensagensRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/manutencao': {
      id: '/owner/manutencao'
      path: '/manutencao'
      fullPath: '/owner/manutencao'
      preLoaderRoute: typeof OwnerManutencaoRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/financeiro': {
      id: '/owner/financeiro'
      path: '/financeiro'
      fullPath: '/owner/financeiro'
      preLoaderRoute: typeof OwnerFinanceiroRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/documentos': {
      id: '/owner/documentos'
      path: '/documentos'
      fullPath: '/owner/documentos'
      preLoaderRoute: typeof OwnerDocumentosRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/imprimir-contrato/$id': {
      id: '/imprimir-contrato/$id'
      path: '/imprimir-contrato/$id'
      fullPath: '/imprimir-contrato/$id'
      preLoaderRoute: typeof ImprimirContratoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casas/$id': {
      id: '/casas/$id'
      path: '/$id'
      fullPath: '/casas/$id'
      preLoaderRoute: typeof CasasIdRouteImport
      parentRoute: typeof CasasRoute
    }
    '/assinar/$documentId': {
      id: '/assinar/$documentId'
      path: '/assinar/$documentId'
      fullPath: '/assinar/$documentId'
      preLoaderRoute: typeof AssinarDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vistorias': {
      id: '/admin/vistorias'
      path: '/vistorias'
      fullPath: '/admin/vistorias'
      preLoaderRoute: typeof AdminVistoriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quartos': {
      id: '/admin/quartos'
      path: '/quartos'
      fullPath: '/admin/quartos'
      preLoaderRoute: typeof AdminQuartosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/proprietarios': {
      id: '/admin/proprietarios'
      path: '/proprietarios'
      fullPath: '/admin/proprietarios'
      preLoaderRoute: typeof AdminProprietariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moradoras': {
      id: '/admin/moradoras'
      path: '/moradoras'
      fullPath: '/admin/moradoras'
      preLoaderRoute: typeof AdminMoradorasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/modelos-contrato': {
      id: '/admin/modelos-contrato'
      path: '/modelos-contrato'
      fullPath: '/admin/modelos-contrato'
      preLoaderRoute: typeof AdminModelosContratoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fornecedores': {
      id: '/admin/fornecedores'
      path: '/fornecedores'
      fullPath: '/admin/fornecedores'
      preLoaderRoute: typeof AdminFornecedoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financeiro': {
      id: '/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contratos': {
      id: '/admin/contratos'
      path: '/contratos'
      fullPath: '/admin/contratos'
      preLoaderRoute: typeof AdminContratosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comunicados': {
      id: '/admin/comunicados'
      path: '/comunicados'
      fullPath: '/admin/comunicados'
      preLoaderRoute: typeof AdminComunicadosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chamados': {
      id: '/admin/chamados'
      path: '/chamados'
      fullPath: '/admin/chamados'
      preLoaderRoute: typeof AdminChamadosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/casas': {
      id: '/admin/casas'
      path: '/casas'
      fullPath: '/admin/casas'
      preLoaderRoute: typeof AdminCasasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/candidaturas': {
      id: '/admin/candidaturas'
      path: '/candidaturas'
      fullPath: '/admin/candidaturas'
      preLoaderRoute: typeof AdminCandidaturasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/acessos': {
      id: '/admin/acessos'
      path: '/acessos'
      fullPath: '/admin/acessos'
      preLoaderRoute: typeof AdminAcessosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contratos/$id': {
      id: '/admin/contratos/$id'
      path: '/$id'
      fullPath: '/admin/contratos/$id'
      preLoaderRoute: typeof AdminContratosIdRouteImport
      parentRoute: typeof AdminContratosRoute
    }
  }
}

interface AdminContratosRouteChildren {
  AdminContratosIdRoute: typeof AdminContratosIdRoute
}

const AdminContratosRouteChildren: AdminContratosRouteChildren = {
  AdminContratosIdRoute: AdminContratosIdRoute,
}

const AdminContratosRouteWithChildren = AdminContratosRoute._addFileChildren(
  AdminContratosRouteChildren,
)

interface AdminRouteChildren {
  AdminAcessosRoute: typeof AdminAcessosRoute
  AdminCandidaturasRoute: typeof AdminCandidaturasRoute
  AdminCasasRoute: typeof AdminCasasRoute
  AdminChamadosRoute: typeof AdminChamadosRoute
  AdminComunicadosRoute: typeof AdminComunicadosRoute
  AdminContratosRoute: typeof AdminContratosRouteWithChildren
  AdminFinanceiroRoute: typeof AdminFinanceiroRoute
  AdminFornecedoresRoute: typeof AdminFornecedoresRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminModelosContratoRoute: typeof AdminModelosContratoRoute
  AdminMoradorasRoute: typeof AdminMoradorasRoute
  AdminProprietariosRoute: typeof AdminProprietariosRoute
  AdminQuartosRoute: typeof AdminQuartosRoute
  AdminVistoriasRoute: typeof AdminVistoriasRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAcessosRoute: AdminAcessosRoute,
  AdminCandidaturasRoute: AdminCandidaturasRoute,
  AdminCasasRoute: AdminCasasRoute,
  AdminChamadosRoute: AdminChamadosRoute,
  AdminComunicadosRoute: AdminComunicadosRoute,
  AdminContratosRoute: AdminContratosRouteWithChildren,
  AdminFinanceiroRoute: AdminFinanceiroRoute,
  AdminFornecedoresRoute: AdminFornecedoresRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminModelosContratoRoute: AdminModelosContratoRoute,
  AdminMoradorasRoute: AdminMoradorasRoute,
  AdminProprietariosRoute: AdminProprietariosRoute,
  AdminQuartosRoute: AdminQuartosRoute,
  AdminVistoriasRoute: AdminVistoriasRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CasasRouteChildren {
  CasasIdRoute: typeof CasasIdRoute
}

const CasasRouteChildren: CasasRouteChildren = {
  CasasIdRoute: CasasIdRoute,
}

const CasasRouteWithChildren = CasasRoute._addFileChildren(CasasRouteChildren)

interface OwnerRouteChildren {
  OwnerDocumentosRoute: typeof OwnerDocumentosRoute
  OwnerFinanceiroRoute: typeof OwnerFinanceiroRoute
  OwnerManutencaoRoute: typeof OwnerManutencaoRoute
  OwnerMensagensRoute: typeof OwnerMensagensRoute
  OwnerVistoriasRoute: typeof OwnerVistoriasRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerDocumentosRoute: OwnerDocumentosRoute,
  OwnerFinanceiroRoute: OwnerFinanceiroRoute,
  OwnerManutencaoRoute: OwnerManutencaoRoute,
  OwnerMensagensRoute: OwnerMensagensRoute,
  OwnerVistoriasRoute: OwnerVistoriasRoute,
  OwnerIndexRoute: OwnerIndexRoute,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

interface PortalRouteChildren {
  PortalChamadosRoute: typeof PortalChamadosRoute
  PortalComunicadosRoute: typeof PortalComunicadosRoute
  PortalComunidadeRoute: typeof PortalComunidadeRoute
  PortalContratosRoute: typeof PortalContratosRoute
  PortalEstadiaRoute: typeof PortalEstadiaRoute
  PortalManualRoute: typeof PortalManualRoute
  PortalPagamentosRoute: typeof PortalPagamentosRoute
  PortalPerfilRoute: typeof PortalPerfilRoute
  PortalRenovacaoRoute: typeof PortalRenovacaoRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalChamadosRoute: PortalChamadosRoute,
  PortalComunicadosRoute: PortalComunicadosRoute,
  PortalComunidadeRoute: PortalComunidadeRoute,
  PortalContratosRoute: PortalContratosRoute,
  PortalEstadiaRoute: PortalEstadiaRoute,
  PortalManualRoute: PortalManualRoute,
  PortalPagamentosRoute: PortalPagamentosRoute,
  PortalPerfilRoute: PortalPerfilRoute,
  PortalRenovacaoRoute: PortalRenovacaoRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CandidaturaRoute: CandidaturaRoute,
  CasasRoute: CasasRouteWithChildren,
  ContatoRoute: ContatoRoute,
  OwnerRoute: OwnerRouteWithChildren,
  PortalRoute: PortalRouteWithChildren,
  ProprietariosRoute: ProprietariosRoute,
  SobreRoute: SobreRoute,
  AssinarDocumentIdRoute: AssinarDocumentIdRoute,
  ImprimirContratoIdRoute: ImprimirContratoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
